title: <p align="center"> Madhu Sudhan Puvvala </p>
logo: /assets/madhu_image.jpeg
description:
  <br>   
  I'm working  as application manager having total 16+ years of experience in Engineering and IT ERP related services.
  and 10+ years of experience in Indian Port ERP application design and implementation. 
  <br>
theme: jekyll-theme-minimal
